<?php

namespace ESP\UserBundle\Repository;

/**
 * DepartmentChiefRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DepartmentChiefRepository extends \Doctrine\ORM\EntityRepository
{
    public function getDepartmentChiefsWithProfessor()
    {
        $qb = $this->createQueryBuilder('dept');
        $qb->leftJoin('dept.professor', 'professor');
        $qb->addSelect('professor'); 


        return $qb->getQuery()->getResult();
    }
}
