<?php

namespace ESP\UserBundle\Repository;

/**
 * HeadTeacherRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HeadTeacherRepository extends \Doctrine\ORM\EntityRepository
{
}
