<?php

namespace ESP\UserBundle\Repository;

/**
 * ProfessorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfessorRepository extends \Doctrine\ORM\EntityRepository
{
    public function getProfessorRelatedToThisToken($confirmationToken)
    {
        $qb = $this->createQueryBuilder('pro');
        $qb->where('pro.confirmationToken LIKE :token');
        $qb->setParameter('token', $confirmationToken);

        return $qb->getQuery()->getOneOrNullResult();
    }

    public function getProfessorsWithDepartmentChief()
    {
        $qb = $this->createQueryBuilder('pro');
        $qb->leftJoin('pro.departmentChief', 'deptChief');
        $qb->addSelect('deptChief');

        return $qb->getQuery()->getResult();
    }
}
