<?php

namespace ESP\SchoolStructureBundle\Repository;


/**
 * CycleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CycleRepository extends \Doctrine\ORM\EntityRepository
{

    public function getCycleWithTheRest($id)
    {
        $qb = $this->createQueryBuilder('c');
        $qb->leftJoin('c.levels', 'lev')->addSelect('lev');
        $qb->leftJoin('c.department', 'dept')->addSelect('dept');
        $qb->leftJoin('c.departmentOption', 'opt')->addSelect('opt');

        $qb->where('c.id = :id');
        $qb->setParameter('id', $id);

        return $qb->getQuery()->getOneOrNullResult();
    }

    public function getAllCyclesWithoutLevelsOrderBy($order)
    {
        if(strcasecmp($order, "asc") == 0 || strcasecmp($order, "desc") == 0)
        {
            $qb = $this->createQueryBuilder('c');
            $qb->leftJoin('c.department', 'dept')->addSelect('dept');
            $qb->leftJoin('c.departmentOption', 'opt')->addSelect('opt');

            $qb->orderBy('c.department', $order);
            $qb->orderBy('c.departmentOption', $order);
            

            return $qb->getQuery()->getResult();
        }else
        {
            return null;
        }

    }
}
