<?php

namespace ESP\SchoolStructureBundle\Repository;

/**
 * DepartmentOptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DepartmentOptionRepository extends \Doctrine\ORM\EntityRepository
{
    public function removeAllDepartmentOptions($id)
    {
        $qb = $this->_em->createQueryBuilder()->delete($this->_entityName,'opt');
        $qb->where('opt.department = :id');
        $qb->setParameter('id',$id);
        
        $qb->getQuery()->execute();
    }
}
