<?php

namespace ESP\SchoolStructureBundle\Repository;

/**
 * DepartmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DepartmentRepository extends \Doctrine\ORM\EntityRepository
{
    public function getDepartmentWithOptions($id)
    {
        $qb = $this->createQueryBuilder('dept')
        ->leftJoin('dept.departmentOptions', 'opt')->addSelect('opt')
        ->where('dept.id = :id');

        $qb->setParameter('id', $id);

        return $qb->getQuery()->getOneOrNullResult();
    }
}
