<?php

namespace ESP\SchoolStructureBundle\Repository;

/**
 * LevelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LevelRepository extends \Doctrine\ORM\EntityRepository
{
    public function removeAllLevels($id)
    {
        $qb = $this->_em->createQueryBuilder()->delete($this->_entityName,'lev');
        $qb->where('lev.cycle = :id');
        $qb->setParameter('id',$id);
        
        $qb->getQuery()->execute();
    }
}
