<?php

namespace ESP\SchoolStructureBundle\Repository;

/**
 * LevelClassRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LevelClassRepository extends \Doctrine\ORM\EntityRepository
{
    
}
